version: '3'

services:
  uao-mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5000"
    volumes:
      - ./:/app
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    environment:
      - MLFLOW_TRACKING_URI=/app/mlruns
    restart: unless-stopped

